AllCops:
  Exclude:
    - db/schema.rb
    - web/node_modules/**/*

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100
  Exclude:
    - db/**/*.rb
    - spec/**/*.rb

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/NestedParenthesizedCalls:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - config/routes.rb
