version: '3'

services:
  ##
  # Application container
  #
  app:
    build: .
    environment:
      - RAILS_ENV=production
      - NODE_ENV=production
    volumes:
      - public:/app/public/
      - sockets:/app/tmp/sockets/
    depends_on:
      - postgres
    links:
      - postgres
    restart: always

  ##
  # Database container
  #
  postgres:
    image: mdillon/postgis:9.6
    volumes:
      - postgres:/var/lib/postgresql/data/
    restart: always

volumes:
  # Public assets (frontend) volume
  public:

  # Database volume
  postgres:

  # App server sockets
  sockets:
