default: &default
  adapter: postgis
  host: localhost
  port: 5432
  schema_search_path: public

development:
  <<: *default
  username: wissle
  password: wissle
  database: wissle

test:
  adapter: sqlite3
  database: db/test.sqlite3

production:
  <<: *default
  username: wissle
  password: wissle
  database: wissle
  pool: 5
